
ROLE_FAMILY_TAXONOMY = {
    "AI_ARCHITECT": {"weights": {"DEEP_LEARNING_GENAI": 5, "MLOPS_DEPLOYMENT": 4, "CLOUD_INFRA": 4, "SYSTEMS_ARCHITECTURE": 5, "PROGRAMMING": 3, "BIG_DATA": 2}, "must_have_any": ["LLM Systems", "Agentic Workflows", "Docker", "Kubernetes", "Architecture Design", "AWS"]},
    "GENAI_DATA_SCIENTIST": {"weights": {"DEEP_LEARNING_GENAI": 5, "PROGRAMMING": 3, "BIG_DATA": 2, "CLOUD_INFRA": 2, "EXPERIMENTATION_RCA": 2}, "must_have_any": ["Transformers", "RAG", "PyTorch", "JAX", "Vector Databases", "RLHF"]},
    "APPLIED_SCIENTIST": {"weights": {"STATISTICS_ML": 4, "DEEP_LEARNING_GENAI": 4, "PROGRAMMING": 3, "EXPERIMENTATION_RCA": 4, "SYSTEMS_ARCHITECTURE": 2}, "must_have_any": ["Feature Engineering", "Experiment Design", "Model Evaluation", "Python"]},
    "CORE_DATA_SCIENTIST": {"weights": {"PROGRAMMING": 4, "STATISTICS_ML": 5, "BIG_DATA": 2, "CLOUD_INFRA": 2, "EXPERIMENTATION_RCA": 3}, "must_have_any": ["Python", "Scikit-learn", "EDA", "Feature Engineering"]},
    "PRODUCT_DATA_SCIENTIST": {"weights": {"PROGRAMMING": 4, "STATISTICS_ML": 4, "PRODUCT_ANALYTICS": 4, "DEEP_LEARNING_GENAI": 2, "EXPERIMENTATION_RCA": 3}, "must_have_any": ["Hypothesis Testing", "Root Cause Analysis", "A/B Testing", "KPI Measurement"]},
    "ML_ENGINEER": {"weights": {"PROGRAMMING": 4, "STATISTICS_ML": 3, "MLOPS_DEPLOYMENT": 4, "CLOUD_INFRA": 3, "SYSTEMS_ARCHITECTURE": 3}, "must_have_any": ["Python", "Model Deployment", "Docker", "CI/CD", "MLflow"]},
    "MLOPS_DATA_SCIENTIST": {"weights": {"MLOPS_DEPLOYMENT": 5, "CLOUD_INFRA": 4, "BIG_DATA": 3, "PROGRAMMING": 3, "STATISTICS_ML": 2}, "must_have_any": ["Docker", "Kubernetes", "MLflow", "Kubeflow", "CI/CD"]},
    "DATA_ENGINEER": {"weights": {"PROGRAMMING": 4, "BIG_DATA": 5, "CLOUD_INFRA": 3, "DATA_MANAGEMENT": 3, "MLOPS_DEPLOYMENT": 2}, "must_have_any": ["PySpark", "SQL", "ETL", "AWS", "Airflow"]},
    "ANALYTICS_ENGINEER": {"weights": {"PROGRAMMING": 3, "BIG_DATA": 4, "DATA_MANAGEMENT": 4, "VISUALIZATION_BI": 3, "PRODUCT_ANALYTICS": 2}, "must_have_any": ["SQL", "dbt", "Dashboarding", "Data Warehousing"]},
    "NLP_LLM_ENGINEER": {"weights": {"DEEP_LEARNING_GENAI": 5, "PROGRAMMING": 4, "SYSTEMS_ARCHITECTURE": 3, "MLOPS_DEPLOYMENT": 3, "CLOUD_INFRA": 2}, "must_have_any": ["Transformers", "RAG", "Prompt Engineering", "LangChain", "Vector Databases"]},
    "COMPUTER_VISION_ENGINEER": {"weights": {"VISION_ROBOTICS": 5, "PROGRAMMING": 4, "SYSTEMS_ARCHITECTURE": 3, "EDGE_EMBEDDED": 3, "MLOPS_DEPLOYMENT": 2}, "must_have_any": ["Computer Vision", "Perception", "PyTorch", "CUDA", "ONNX Runtime"]},
    "ROBOTICS_AUTONOMY_ENGINEER": {"weights": {"VISION_ROBOTICS": 4, "EDGE_EMBEDDED": 5, "SYSTEMS_ARCHITECTURE": 4, "PROGRAMMING": 3, "MLOPS_DEPLOYMENT": 2}, "must_have_any": ["Robotics", "Navigation", "Sensor Fusion", "ROS2", "Embedded AI"]},
    "QUANT_DATA_ANALYST": {"weights": {"DOMAIN_FINANCE": 5, "STATISTICS_ML": 4, "PROGRAMMING": 3, "VISUALIZATION_BI": 3}, "must_have_any": ["Time Series Forecasting", "Monte Carlo Simulation", "Sharpe Ratio", "SQL"]},
    "RETAIL_ANALYTICS": {"weights": {"DOMAIN_RETAIL": 5, "STATISTICS_ML": 4, "PROGRAMMING": 4, "BIG_DATA": 3, "VISUALIZATION_BI": 2}, "must_have_any": ["Demand Forecasting", "Price Elasticity", "Inventory Optimization", "SQL"]},
    "MARKETING_ANALYTICS": {"weights": {"DOMAIN_MARKETING": 5, "STATISTICS_ML": 3, "PROGRAMMING": 3, "VISUALIZATION_BI": 3, "PRODUCT_ANALYTICS": 2}, "must_have_any": ["Attribution Modeling", "MMM", "GA4", "SQL"]},
    "SUPPLY_CHAIN_ANALYTICS": {"weights": {"DOMAIN_SUPPLY_CHAIN": 5, "STATISTICS_ML": 3, "PROGRAMMING": 4, "BIG_DATA": 3, "VISUALIZATION_BI": 2}, "must_have_any": ["MILP", "Network Optimization", "Inventory Optimization", "Pyomo"]},
    "DATA_ANALYST": {"weights": {"VISUALIZATION_BI": 5, "STATISTICS_ML": 4, "PROGRAMMING": 3, "DATA_MANAGEMENT": 3}, "must_have_any": ["SQL", "Excel", "Dashboarding", "Power BI", "Tableau"]},
    "ANALYTICS_MANAGER": {"weights": {"PRODUCT_ANALYTICS": 4, "STATISTICS_ML": 4, "VISUALIZATION_BI": 3, "PROGRAMMING": 2}, "must_have_any": ["KPI Measurement", "A/B Testing", "Hypothesis Testing", "Dashboarding"]},
    "PLATFORM_ENGINEER": {"weights": {"SYSTEMS_ARCHITECTURE": 5, "CLOUD_INFRA": 5, "MLOPS_DEPLOYMENT": 4, "BIG_DATA": 3}, "must_have_any": ["Kubernetes", "Terraform", "CI/CD", "Docker", "Cloud Engineering"]},
    "RESEARCH_SCIENTIST": {"weights": {"STATISTICS_ML": 5, "DEEP_LEARNING_GENAI": 5, "EXPERIMENTATION_RCA": 4, "PROGRAMMING": 3}, "must_have_any": ["PyTorch", "JAX", "Experiment Design", "Causal Inference", "Feature Engineering"]},
    "GENERALIST_DATA": {"weights": {"PROGRAMMING": 3, "STATISTICS_ML": 3, "VISUALIZATION_BI": 3, "BIG_DATA": 2}, "must_have_any": ["Python", "SQL", "EDA", "Dashboarding"]},
}

ROLE_DNA_AFFINITY = {
    "AI_ARCHITECT": "PRODUCT",
    "GENAI_DATA_SCIENTIST": "PRODUCT",
    "CORE_DATA_SCIENTIST": "HYBRID",
    "APPLIED_SCIENTIST": "HYBRID",
    "PRODUCT_DATA_SCIENTIST": "PRODUCT",
    "ML_ENGINEER": "PRODUCT",
    "MLOPS_DATA_SCIENTIST": "PRODUCT",
    "DATA_ENGINEER": "HYBRID",
    "ANALYTICS_ENGINEER": "HYBRID",
    "NLP_LLM_ENGINEER": "PRODUCT",
    "COMPUTER_VISION_ENGINEER": "PRODUCT",
    "ROBOTICS_AUTONOMY_ENGINEER": "PRODUCT",
    "QUANT_DATA_ANALYST": "DOMAIN_SPECIALIST",
    "RETAIL_ANALYTICS": "DOMAIN_SPECIALIST",
    "MARKETING_ANALYTICS": "DOMAIN_SPECIALIST",
    "SUPPLY_CHAIN_ANALYTICS": "DOMAIN_SPECIALIST",
    "DATA_ANALYST": "CONSULTING",
    "ANALYTICS_MANAGER": "CONSULTING",
    "PLATFORM_ENGINEER": "PRODUCT",
    "RESEARCH_SCIENTIST": "HYBRID",
    "GENERALIST_DATA": "HYBRID",
}

DOMAIN_FIT_MAP = {
    "QUANT_DATA_ANALYST": {"required": ["BFSI"], "preferred": []},
    "RETAIL_ANALYTICS": {"required": ["RETAIL", "ECOMMERCE"], "preferred": ["SUPPLY_CHAIN"]},
    "MARKETING_ANALYTICS": {"required": ["ECOMMERCE", "RETAIL"], "preferred": ["BFSI"]},
    "SUPPLY_CHAIN_ANALYTICS": {"required": ["SUPPLY_CHAIN", "MANUFACTURING"], "preferred": ["RETAIL"]},
}

ROLE_CORE_SKILLS = {
    "AI_ARCHITECT": ["LLM Systems", "Docker", "Architecture Design"],
    "CORE_DATA_SCIENTIST": ["Python", "Scikit-learn", "Feature Engineering"],
    "ML_ENGINEER": ["Python", "Model Deployment", "Docker"],
    "DATA_ENGINEER": ["PySpark", "SQL", "Airflow"],
    "NLP_LLM_ENGINEER": ["Transformers", "RAG", "Python"],
    "GENAI_DATA_SCIENTIST": ["PyTorch", "RAG", "LLM Systems"],
    "MLOPS_DATA_SCIENTIST": ["Docker", "Kubernetes", "MLflow"],
    "ANALYTICS_ENGINEER": ["SQL", "dbt", "Data Warehousing"],
    "COMPUTER_VISION_ENGINEER": ["Computer Vision", "PyTorch", "CUDA"],
    "ROBOTICS_AUTONOMY_ENGINEER": ["Robotics", "ROS2", "Sensor Fusion"],
    "DATA_ANALYST": ["SQL", "Excel", "Dashboarding"],
    "PLATFORM_ENGINEER": ["Kubernetes", "Terraform", "CI/CD"],
    "QUANT_DATA_ANALYST": ["SQL", "Python", "Sharpe Ratio"],
    "RETAIL_ANALYTICS": ["SQL", "Demand Forecasting", "Python"],
    "MARKETING_ANALYTICS": ["SQL", "Attribution Modeling", "GA4"],
    "SUPPLY_CHAIN_ANALYTICS": ["Python", "Inventory Optimization", "MILP"],
    "APPLIED_SCIENTIST": ["Python", "Feature Engineering", "Experiment Design"],
    "PRODUCT_DATA_SCIENTIST": ["A/B Testing", "Python", "KPI Measurement"],
    "RESEARCH_SCIENTIST": ["PyTorch", "Experiment Design", "Python"],
    "ANALYTICS_MANAGER": ["SQL", "KPI Measurement", "Dashboarding"],
    "GENERALIST_DATA": ["Python", "SQL", "EDA"],
}

CANONICAL_SKILL_MAP = {
    "python": ("Python", "PROGRAMMING"), "pyspark": ("PySpark", "PROGRAMMING"), "r": ("R", "PROGRAMMING"), "sql": ("SQL", "PROGRAMMING"), "java": ("Java", "PROGRAMMING"), "scala": ("Scala", "PROGRAMMING"), "c": ("C", "PROGRAMMING"), "c++": ("C++", "PROGRAMMING"), "matlab": ("MATLAB", "PROGRAMMING"), "julia": ("Julia", "PROGRAMMING"), "bash": ("Bash", "PROGRAMMING"),
    "pandas": ("Pandas", "PROGRAMMING"), "numpy": ("NumPy", "PROGRAMMING"), "scipy": ("SciPy", "PROGRAMMING"), "fastapi": ("FastAPI", "PROGRAMMING"), "flask": ("Flask", "PROGRAMMING"), "rest api": ("REST APIs", "PROGRAMMING"), "rest apis": ("REST APIs", "PROGRAMMING"), "api development": ("API Development", "PROGRAMMING"), "microservices": ("Microservices", "PROGRAMMING"), "json": ("JSON", "PROGRAMMING"),

    "sklearn": ("Scikit-learn", "STATISTICS_ML"), "scikit-learn": ("Scikit-learn", "STATISTICS_ML"), "xgboost": ("XGBoost", "STATISTICS_ML"), "lightgbm": ("LightGBM", "STATISTICS_ML"), "catboost": ("CatBoost", "STATISTICS_ML"), "random forest": ("Random Forest", "STATISTICS_ML"), "regression": ("Regression", "STATISTICS_ML"), "classification": ("Classification", "STATISTICS_ML"), "clustering": ("Clustering", "STATISTICS_ML"), "forecasting": ("Forecasting", "STATISTICS_ML"), "time series": ("Time Series Forecasting", "STATISTICS_ML"), "time series analysis": ("Time Series Forecasting", "STATISTICS_ML"), "time series forecasting": ("Time Series Forecasting", "STATISTICS_ML"), "arima": ("ARIMA", "STATISTICS_ML"), "sarimax": ("SARIMAX", "STATISTICS_ML"), "prophet": ("Prophet", "STATISTICS_ML"), "monte carlo": ("Monte Carlo Simulation", "STATISTICS_ML"), "bayesian": ("Bayesian Modeling", "STATISTICS_ML"), "recommendation systems": ("Recommendation Systems", "STATISTICS_ML"), "recommendation": ("Recommendation Systems", "STATISTICS_ML"), "customer segmentation": ("Customer Segmentation", "STATISTICS_ML"), "ner": ("Named Entity Recognition", "STATISTICS_ML"), "named entity recognition": ("Named Entity Recognition", "STATISTICS_ML"), "topic modeling": ("Topic Modeling", "STATISTICS_ML"), "sentiment analysis": ("Sentiment Analysis", "STATISTICS_ML"), "feature engineering": ("Feature Engineering", "STATISTICS_ML"), "data cleaning": ("Data Cleaning", "STATISTICS_ML"), "data transformation": ("Data Transformation", "STATISTICS_ML"), "model evaluation": ("Model Evaluation", "STATISTICS_ML"), "model tuning": ("Model Tuning", "STATISTICS_ML"), "hyperparameter tuning": ("Hyperparameter Tuning", "STATISTICS_ML"), "customer lifetime value": ("Customer Lifetime Value", "STATISTICS_ML"),

    "eda": ("EDA", "EXPERIMENTATION_RCA"), "a/b": ("A/B Testing", "EXPERIMENTATION_RCA"), "ab testing": ("A/B Testing", "EXPERIMENTATION_RCA"), "a/b testing": ("A/B Testing", "EXPERIMENTATION_RCA"), "hypothesis testing": ("Hypothesis Testing", "EXPERIMENTATION_RCA"), "root cause analysis": ("Root Cause Analysis", "EXPERIMENTATION_RCA"), "statistical analysis": ("Statistical Analysis", "EXPERIMENTATION_RCA"), "factor analysis": ("Factor Analysis", "EXPERIMENTATION_RCA"), "experiment design": ("Experiment Design", "EXPERIMENTATION_RCA"), "causal inference": ("Causal Inference", "EXPERIMENTATION_RCA"), "explainable ai": ("Explainable AI", "EXPERIMENTATION_RCA"),

    "pytorch": ("PyTorch", "DEEP_LEARNING_GENAI"), "tensorflow": ("TensorFlow", "DEEP_LEARNING_GENAI"), "jax": ("JAX", "DEEP_LEARNING_GENAI"), "keras": ("Keras", "DEEP_LEARNING_GENAI"), "transformers": ("Transformers", "DEEP_LEARNING_GENAI"), "hugging face transformers": ("Transformers", "DEEP_LEARNING_GENAI"), "sentence transformers": ("Sentence Transformers", "DEEP_LEARNING_GENAI"), "bert": ("BERT", "DEEP_LEARNING_GENAI"), "llm": ("LLM Systems", "DEEP_LEARNING_GENAI"), "llms": ("LLM Systems", "DEEP_LEARNING_GENAI"), "slms": ("SLM Systems", "DEEP_LEARNING_GENAI"), "gpt": ("LLM Systems", "DEEP_LEARNING_GENAI"), "gpt-4": ("LLM Systems", "DEEP_LEARNING_GENAI"), "openai api": ("OpenAI API", "DEEP_LEARNING_GENAI"), "openai gpt": ("LLM Systems", "DEEP_LEARNING_GENAI"), "prompt engineering": ("Prompt Engineering", "DEEP_LEARNING_GENAI"), "rag": ("RAG", "DEEP_LEARNING_GENAI"), "retrieval-augmented generation": ("RAG", "DEEP_LEARNING_GENAI"), "vector database": ("Vector Databases", "DEEP_LEARNING_GENAI"), "vector databases": ("Vector Databases", "DEEP_LEARNING_GENAI"), "vector store": ("Vector Databases", "DEEP_LEARNING_GENAI"), "vector stores": ("Vector Databases", "DEEP_LEARNING_GENAI"), "faiss": ("FAISS", "DEEP_LEARNING_GENAI"), "langchain": ("LangChain", "DEEP_LEARNING_GENAI"), "langgraph": ("LangGraph", "DEEP_LEARNING_GENAI"), "llamaindex": ("LlamaIndex", "DEEP_LEARNING_GENAI"), "autogen": ("AutoGen", "DEEP_LEARNING_GENAI"), "agentic": ("Agentic Workflows", "DEEP_LEARNING_GENAI"), "agentic ai": ("Agentic Workflows", "DEEP_LEARNING_GENAI"), "multi-agent": ("Multi-Agent Systems", "DEEP_LEARNING_GENAI"), "multi-agent systems": ("Multi-Agent Systems", "DEEP_LEARNING_GENAI"), "react": ("ReAct", "DEEP_LEARNING_GENAI"), "tool calling": ("Tool Calling", "DEEP_LEARNING_GENAI"), "memory management": ("Memory Management", "DEEP_LEARNING_GENAI"), "rlhf": ("RLHF", "DEEP_LEARNING_GENAI"), "fine-tuning": ("Fine-tuning", "DEEP_LEARNING_GENAI"), "diffusion": ("Diffusion Models", "DEEP_LEARNING_GENAI"), "generative ai": ("Generative AI", "DEEP_LEARNING_GENAI"), "google adk": ("Google ADK", "DEEP_LEARNING_GENAI"),

    "spark": ("Spark", "BIG_DATA"), "hadoop": ("Hadoop", "BIG_DATA"), "snowflake": ("Snowflake", "BIG_DATA"), "dask": ("Dask", "BIG_DATA"), "edw": ("EDW", "BIG_DATA"), "etl": ("ETL", "BIG_DATA"), "elt": ("ELT", "BIG_DATA"), "dbt": ("dbt", "BIG_DATA"), "airflow": ("Airflow", "BIG_DATA"), "composer airflow": ("Airflow", "BIG_DATA"), "data pipeline": ("Data Pipelines", "BIG_DATA"), "data pipelines": ("Data Pipelines", "BIG_DATA"), "ml pipeline": ("Data Pipelines", "BIG_DATA"), "ml pipelines": ("Data Pipelines", "BIG_DATA"), "training pipeline": ("Data Pipelines", "BIG_DATA"), "training pipelines": ("Data Pipelines", "BIG_DATA"), "inference pipeline": ("Data Pipelines", "BIG_DATA"), "inference pipelines": ("Data Pipelines", "BIG_DATA"), "feature pipeline": ("Data Pipelines", "BIG_DATA"), "feature pipelines": ("Data Pipelines", "BIG_DATA"), "data infrastructure": ("Data Infrastructure", "BIG_DATA"), "big data": ("Big Data Analytics", "BIG_DATA"), "stream processing": ("Stream Processing", "BIG_DATA"), "batch processing": ("Batch Processing", "BIG_DATA"), "kafka": ("Kafka", "BIG_DATA"), "redis streams": ("Redis Streams", "BIG_DATA"),

    "aws": ("AWS", "CLOUD_INFRA"), "s3": ("S3", "CLOUD_INFRA"), "ec2": ("EC2", "CLOUD_INFRA"), "sagemaker": ("SageMaker", "CLOUD_INFRA"), "redshift": ("Redshift", "CLOUD_INFRA"), "glue": ("Glue", "CLOUD_INFRA"), "lambda": ("Lambda", "CLOUD_INFRA"), "azure": ("Azure", "CLOUD_INFRA"), "azure ml studio": ("Azure ML Studio", "CLOUD_INFRA"), "gcp": ("GCP", "CLOUD_INFRA"), "vertex ai": ("Vertex AI", "CLOUD_INFRA"), "gcp vertex ai": ("Vertex AI", "CLOUD_INFRA"), "google cloud run": ("Cloud Run", "CLOUD_INFRA"), "cloud run": ("Cloud Run", "CLOUD_INFRA"), "google cloud tasks": ("Cloud Tasks", "CLOUD_INFRA"), "cloud solutions": ("Cloud Solutions", "CLOUD_INFRA"), "terraform": ("Terraform", "CLOUD_INFRA"), "eks": ("EKS", "CLOUD_INFRA"), "ecr": ("ECR", "CLOUD_INFRA"), "cloud engineering": ("Cloud Engineering", "CLOUD_INFRA"),

    "docker": ("Docker", "MLOPS_DEPLOYMENT"), "kubernetes": ("Kubernetes", "MLOPS_DEPLOYMENT"), "k8s": ("Kubernetes", "MLOPS_DEPLOYMENT"), "mlflow": ("MLflow", "MLOPS_DEPLOYMENT"), "kubeflow": ("Kubeflow", "MLOPS_DEPLOYMENT"), "ci/cd": ("CI/CD", "MLOPS_DEPLOYMENT"), "github actions": ("GitHub Actions", "MLOPS_DEPLOYMENT"), "jenkins": ("Jenkins", "MLOPS_DEPLOYMENT"), "gitlab": ("GitLab CI/CD", "MLOPS_DEPLOYMENT"), "dvc": ("DVC", "MLOPS_DEPLOYMENT"), "weights & biases": ("Weights & Biases", "MLOPS_DEPLOYMENT"), "wandb": ("Weights & Biases", "MLOPS_DEPLOYMENT"), "drift": ("Drift Monitoring", "MLOPS_DEPLOYMENT"), "training-serving skew": ("Training-Serving Skew", "MLOPS_DEPLOYMENT"), "model deployment": ("Model Deployment", "MLOPS_DEPLOYMENT"), "production systems": ("Production Systems", "MLOPS_DEPLOYMENT"), "production-ready": ("Production Systems", "MLOPS_DEPLOYMENT"), "monitoring": ("Monitoring", "MLOPS_DEPLOYMENT"), "retraining": ("Model Retraining", "MLOPS_DEPLOYMENT"), "inference optimization": ("Inference Optimization", "MLOPS_DEPLOYMENT"),

    "tableau": ("Tableau", "VISUALIZATION_BI"), "power bi": ("Power BI", "VISUALIZATION_BI"), "matplotlib": ("Matplotlib", "VISUALIZATION_BI"), "seaborn": ("Seaborn", "VISUALIZATION_BI"), "plotly": ("Plotly", "VISUALIZATION_BI"), "dash": ("Dash", "VISUALIZATION_BI"), "streamlit": ("Streamlit", "VISUALIZATION_BI"), "looker": ("Looker", "VISUALIZATION_BI"), "looker studio": ("Looker Studio", "VISUALIZATION_BI"), "excel": ("Excel", "VISUALIZATION_BI"), "vba": ("VBA", "VISUALIZATION_BI"), "dashboard": ("Dashboarding", "VISUALIZATION_BI"), "dashboards": ("Dashboarding", "VISUALIZATION_BI"), "data visualization": ("Data Visualization", "VISUALIZATION_BI"),

    "product analytics": ("Product Analytics", "PRODUCT_ANALYTICS"), "retention": ("Retention Analytics", "PRODUCT_ANALYTICS"), "kpi": ("KPI Measurement", "PRODUCT_ANALYTICS"), "customer feedback": ("Customer Feedback Analysis", "PRODUCT_ANALYTICS"), "sales metrics": ("Sales Metrics Analysis", "PRODUCT_ANALYTICS"), "iot data": ("IoT Data Analysis", "PRODUCT_ANALYTICS"), "growth": ("Growth Analytics", "PRODUCT_ANALYTICS"), "funnel": ("Funnel Analytics", "PRODUCT_ANALYTICS"),

    "data warehousing": ("Data Warehousing", "DATA_MANAGEMENT"), "data modeling": ("Data Modeling", "DATA_MANAGEMENT"), "data quality": ("Data Quality", "DATA_MANAGEMENT"), "postgresql": ("PostgreSQL", "DATA_MANAGEMENT"), "mysql": ("MySQL", "DATA_MANAGEMENT"), "nosql": ("NoSQL", "DATA_MANAGEMENT"),

    "architecture": ("Architecture Design", "SYSTEMS_ARCHITECTURE"), "system design": ("System Design", "SYSTEMS_ARCHITECTURE"), "architecture design": ("Architecture Design", "SYSTEMS_ARCHITECTURE"), "scalable": ("Scalable Systems", "SYSTEMS_ARCHITECTURE"), "distributed systems": ("Distributed Systems", "SYSTEMS_ARCHITECTURE"), "platform engineering": ("Platform Engineering", "SYSTEMS_ARCHITECTURE"), "modular": ("Modular Design", "SYSTEMS_ARCHITECTURE"), "production architecture": ("Production Architecture", "SYSTEMS_ARCHITECTURE"),

    "robotics": ("Robotics", "VISION_ROBOTICS"), "autonomy": ("Autonomous Systems", "VISION_ROBOTICS"), "computer vision": ("Computer Vision", "VISION_ROBOTICS"), "perception": ("Perception", "VISION_ROBOTICS"), "navigation": ("Navigation", "VISION_ROBOTICS"), "sensor fusion": ("Sensor Fusion", "VISION_ROBOTICS"), "eo/ir": ("EO/IR", "VISION_ROBOTICS"), "multispectral": ("Multispectral Analytics", "VISION_ROBOTICS"), "remote sensing": ("Remote Sensing", "VISION_ROBOTICS"), "uav": ("UAV", "VISION_ROBOTICS"), "ugv": ("UGV", "VISION_ROBOTICS"), "bev": ("Birds Eye View", "VISION_ROBOTICS"), "vio": ("Visual Inertial Odometry", "VISION_ROBOTICS"), "slam": ("SLAM", "VISION_ROBOTICS"), "pat": ("Precision Aerial Targeting", "VISION_ROBOTICS"), "aerospace": ("Aerospace", "VISION_ROBOTICS"),

    "embedded ai": ("Embedded AI", "EDGE_EMBEDDED"), "embedded compute": ("Embedded Compute", "EDGE_EMBEDDED"), "nvidia jetson": ("NVIDIA Jetson", "EDGE_EMBEDDED"), "qualcomm": ("Qualcomm Edge", "EDGE_EMBEDDED"), "cuda": ("CUDA", "EDGE_EMBEDDED"), "tensorrt": ("TensorRT", "EDGE_EMBEDDED"), "onnx runtime": ("ONNX Runtime", "EDGE_EMBEDDED"), "openvino": ("OpenVINO", "EDGE_EMBEDDED"), "arm cortex": ("ARM Cortex", "EDGE_EMBEDDED"), "stm32": ("STM32", "EDGE_EMBEDDED"), "rtos": ("RTOS", "EDGE_EMBEDDED"), "fpga": ("FPGA", "EDGE_EMBEDDED"),

    "sharpe": ("Sharpe Ratio", "DOMAIN_FINANCE"), "beta": ("Beta", "DOMAIN_FINANCE"), "greeks": ("Greeks", "DOMAIN_FINANCE"), "risk parity": ("Risk Parity", "DOMAIN_FINANCE"), "derivatives": ("Derivatives", "DOMAIN_FINANCE"), "fixed income": ("Fixed Income", "DOMAIN_FINANCE"), "mutual funds": ("Mutual Funds", "DOMAIN_FINANCE"), "portfolio": ("Portfolio Analytics", "DOMAIN_FINANCE"),
    "demand forecasting": ("Demand Forecasting", "DOMAIN_RETAIL"), "price elasticity": ("Price Elasticity", "DOMAIN_RETAIL"), "inventory turnover": ("Inventory Turnover", "DOMAIN_RETAIL"), "gmv": ("GMV", "DOMAIN_RETAIL"), "clickstream": ("Clickstream", "DOMAIN_RETAIL"), "pos": ("POS", "DOMAIN_RETAIL"), "market basket": ("Market Basket Analysis", "DOMAIN_RETAIL"), "sku": ("SKU Analytics", "DOMAIN_RETAIL"), "churn": ("Churn Modeling", "DOMAIN_RETAIL"),
    "attribution": ("Attribution Modeling", "DOMAIN_MARKETING"), "marketing mix modeling": ("MMM", "DOMAIN_MARKETING"), "mmm": ("MMM", "DOMAIN_MARKETING"), "rfm": ("RFM Analysis", "DOMAIN_MARKETING"), "ga4": ("GA4", "DOMAIN_MARKETING"), "gtm": ("GTM", "DOMAIN_MARKETING"), "google ads": ("Google Ads", "DOMAIN_MARKETING"), "meta ads": ("Meta Ads", "DOMAIN_MARKETING"),
    "milp": ("MILP", "DOMAIN_SUPPLY_CHAIN"), "network optimization": ("Network Optimization", "DOMAIN_SUPPLY_CHAIN"), "inventory optimization": ("Inventory Optimization", "DOMAIN_SUPPLY_CHAIN"), "meio": ("MEIO", "DOMAIN_SUPPLY_CHAIN"), "pyomo": ("Pyomo", "DOMAIN_SUPPLY_CHAIN"), "gurobi": ("Gurobi", "DOMAIN_SUPPLY_CHAIN"), "pulp": ("PuLP", "DOMAIN_SUPPLY_CHAIN"), "simpy": ("SimPy", "DOMAIN_SUPPLY_CHAIN"), "wms": ("WMS", "DOMAIN_SUPPLY_CHAIN"), "incoterms": ("Incoterms", "DOMAIN_SUPPLY_CHAIN"), "logistics": ("Logistics Analytics", "DOMAIN_SUPPLY_CHAIN"),

    "crewai": ("CrewAI", "DEEP_LEARNING_GENAI"), "smolagents": ("SmolAgents", "DEEP_LEARNING_GENAI"), "anthropic claude": ("Claude API", "DEEP_LEARNING_GENAI"), "gemini": ("Gemini", "DEEP_LEARNING_GENAI"), "mistral": ("Mistral", "DEEP_LEARNING_GENAI"), "ollama": ("Ollama", "DEEP_LEARNING_GENAI"), "vllm": ("vLLM", "MLOPS_DEPLOYMENT"), "triton": ("Triton Inference Server", "MLOPS_DEPLOYMENT"), "ray serve": ("Ray Serve", "MLOPS_DEPLOYMENT"), "bentoml": ("BentoML", "MLOPS_DEPLOYMENT"),
    "celery": ("Celery", "BIG_DATA"), "rabbitmq": ("RabbitMQ", "BIG_DATA"),
    "neo4j": ("Neo4j", "DATA_MANAGEMENT"), "pinecone": ("Pinecone", "DEEP_LEARNING_GENAI"), "weaviate": ("Weaviate", "DEEP_LEARNING_GENAI"), "qdrant": ("Qdrant", "DEEP_LEARNING_GENAI"), "chroma": ("Chroma", "DEEP_LEARNING_GENAI"),
    "databricks": ("Databricks", "BIG_DATA"), "delta lake": ("Delta Lake", "BIG_DATA"), "apache iceberg": ("Apache Iceberg", "BIG_DATA"),
    "great expectations": ("Great Expectations", "DATA_MANAGEMENT"), "feast": ("Feast", "MLOPS_DEPLOYMENT"), "zenml": ("ZenML", "MLOPS_DEPLOYMENT"),

    # ── Additional programming languages & frameworks ──
    "go": ("Go", "PROGRAMMING"), "golang": ("Go", "PROGRAMMING"),
    "rust": ("Rust", "PROGRAMMING"), "swift": ("Swift", "PROGRAMMING"),
    "kotlin": ("Kotlin", "PROGRAMMING"), "dart": ("Dart", "PROGRAMMING"),
    "typescript": ("TypeScript", "PROGRAMMING"), "javascript": ("JavaScript", "PROGRAMMING"),
    "node.js": ("Node.js", "PROGRAMMING"), "nodejs": ("Node.js", "PROGRAMMING"),
    "django": ("Django", "PROGRAMMING"), "spring boot": ("Spring Boot", "PROGRAMMING"),
    "graphql": ("GraphQL", "PROGRAMMING"), "grpc": ("gRPC", "PROGRAMMING"),
    "asyncio": ("AsyncIO", "PROGRAMMING"),
    "pydantic": ("Pydantic", "PROGRAMMING"), "sqlalchemy": ("SQLAlchemy", "PROGRAMMING"),
    "pytest": ("PyTest", "PROGRAMMING"), "unit testing": ("Unit Testing", "PROGRAMMING"),
    "integration testing": ("Integration Testing", "PROGRAMMING"),
    "ruby": ("Ruby", "PROGRAMMING"), "php": ("PHP", "PROGRAMMING"),
    "perl": ("Perl", "PROGRAMMING"), "haskell": ("Haskell", "PROGRAMMING"),
    "elixir": ("Elixir", "PROGRAMMING"), "erlang": ("Erlang", "PROGRAMMING"),
    "cobol": ("COBOL", "PROGRAMMING"), "fortran": ("Fortran", "PROGRAMMING"),
    "shell scripting": ("Shell Scripting", "PROGRAMMING"),
    "powershell": ("PowerShell", "PROGRAMMING"),
    "git": ("Git", "PROGRAMMING"), "github": ("GitHub", "PROGRAMMING"),
    "bitbucket": ("Bitbucket", "PROGRAMMING"),
    "object-oriented": ("OOP", "PROGRAMMING"), "oop": ("OOP", "PROGRAMMING"),
    "functional programming": ("Functional Programming", "PROGRAMMING"),
    "design patterns": ("Design Patterns", "PROGRAMMING"),
    "solid principles": ("SOLID Principles", "PROGRAMMING"),
    "tdd": ("TDD", "PROGRAMMING"), "bdd": ("BDD", "PROGRAMMING"),
    "swagger": ("Swagger/OpenAPI", "PROGRAMMING"), "openapi": ("Swagger/OpenAPI", "PROGRAMMING"),
    "websocket": ("WebSockets", "PROGRAMMING"), "websockets": ("WebSockets", "PROGRAMMING"),

    # ── Additional ML/Stats ──
    "gradient boosting": ("Gradient Boosting", "STATISTICS_ML"),
    "adaboost": ("AdaBoost", "STATISTICS_ML"),
    "svm": ("SVM", "STATISTICS_ML"), "support vector machine": ("SVM", "STATISTICS_ML"),
    "knn": ("KNN", "STATISTICS_ML"), "naive bayes": ("Naive Bayes", "STATISTICS_ML"),
    "logistic regression": ("Logistic Regression", "STATISTICS_ML"),
    "linear regression": ("Linear Regression", "STATISTICS_ML"),
    "pca": ("PCA", "STATISTICS_ML"), "dimensionality reduction": ("Dimensionality Reduction", "STATISTICS_ML"),
    "anomaly detection": ("Anomaly Detection", "STATISTICS_ML"),
    "fraud detection": ("Fraud Detection", "STATISTICS_ML"),
    "survival analysis": ("Survival Analysis", "STATISTICS_ML"),
    "cox regression": ("Cox Regression", "STATISTICS_ML"),
    "uplift modeling": ("Uplift Modeling", "STATISTICS_ML"),
    "multi-armed bandit": ("Multi-Armed Bandit", "STATISTICS_ML"),
    "reinforcement learning": ("Reinforcement Learning", "STATISTICS_ML"),
    "q-learning": ("Q-Learning", "STATISTICS_ML"),
    "double ml": ("Double ML", "STATISTICS_ML"),
    "did": ("Difference-in-Differences", "STATISTICS_ML"),
    "difference in differences": ("Difference-in-Differences", "STATISTICS_ML"),
    "regression discontinuity": ("Regression Discontinuity", "STATISTICS_ML"),
    "matching estimators": ("Matching Estimators", "STATISTICS_ML"),
    "shapley": ("SHAP", "STATISTICS_ML"), "shap": ("SHAP", "STATISTICS_ML"),
    "lime": ("LIME", "STATISTICS_ML"),
    "class imbalance": ("Class Imbalance Handling", "STATISTICS_ML"),
    "smote": ("SMOTE", "STATISTICS_ML"),
    "cross validation": ("Cross Validation", "STATISTICS_ML"),
    "grid search": ("Grid Search CV", "STATISTICS_ML"),
    "optuna": ("Optuna", "STATISTICS_ML"), "ray tune": ("Ray Tune", "STATISTICS_ML"),
    "statsmodels": ("StatsModels", "STATISTICS_ML"),
    "roc auc": ("ROC-AUC", "STATISTICS_ML"), "precision recall": ("Precision-Recall", "STATISTICS_ML"),
    "nlg": ("NLG", "STATISTICS_ML"), "nlu": ("NLU", "STATISTICS_ML"),
    "text classification": ("Text Classification", "STATISTICS_ML"),
    "sequence labeling": ("Sequence Labeling", "STATISTICS_ML"),
    "coreference resolution": ("Coreference Resolution", "STATISTICS_ML"),
    "relation extraction": ("Relation Extraction", "STATISTICS_ML"),

    # ── GenAI / LLM extras ──
    "claude": ("Claude API", "DEEP_LEARNING_GENAI"),
    "claude api": ("Claude API", "DEEP_LEARNING_GENAI"),
    "anthropic": ("Anthropic", "DEEP_LEARNING_GENAI"),
    "llama": ("LLaMA", "DEEP_LEARNING_GENAI"), "llama 2": ("LLaMA", "DEEP_LEARNING_GENAI"),
    "llama 3": ("LLaMA", "DEEP_LEARNING_GENAI"),
    "mistral ai": ("Mistral", "DEEP_LEARNING_GENAI"),
    "phi": ("Phi Models", "DEEP_LEARNING_GENAI"), "phi-3": ("Phi Models", "DEEP_LEARNING_GENAI"),
    "gemma": ("Gemma", "DEEP_LEARNING_GENAI"),
    "cohere": ("Cohere", "DEEP_LEARNING_GENAI"),
    "openrouter": ("OpenRouter", "DEEP_LEARNING_GENAI"),
    "together ai": ("Together AI", "DEEP_LEARNING_GENAI"),
    "replicate": ("Replicate", "DEEP_LEARNING_GENAI"),
    "groq": ("Groq", "DEEP_LEARNING_GENAI"),
    "bedrock": ("AWS Bedrock", "DEEP_LEARNING_GENAI"),
    "azure openai": ("Azure OpenAI", "DEEP_LEARNING_GENAI"),
    "embeddings": ("Embeddings", "DEEP_LEARNING_GENAI"),
    "semantic search": ("Semantic Search", "DEEP_LEARNING_GENAI"),
    "knowledge graph": ("Knowledge Graphs", "DEEP_LEARNING_GENAI"),
    "guardrails": ("LLM Guardrails", "DEEP_LEARNING_GENAI"),
    "red teaming": ("LLM Red Teaming", "DEEP_LEARNING_GENAI"),
    "constitutional ai": ("Constitutional AI", "DEEP_LEARNING_GENAI"),
    "function calling": ("Function Calling", "DEEP_LEARNING_GENAI"),
    "structured output": ("Structured Output", "DEEP_LEARNING_GENAI"),
    "mcp": ("MCP Protocol", "DEEP_LEARNING_GENAI"),
    "a2a": ("A2A Protocol", "DEEP_LEARNING_GENAI"),
    "text to sql": ("Text-to-SQL", "DEEP_LEARNING_GENAI"),
    "text to image": ("Text-to-Image", "DEEP_LEARNING_GENAI"),
    "stable diffusion": ("Stable Diffusion", "DEEP_LEARNING_GENAI"),
    "midjourney": ("Midjourney", "DEEP_LEARNING_GENAI"),
    "dalle": ("DALL-E", "DEEP_LEARNING_GENAI"),
    "whisper": ("Whisper ASR", "DEEP_LEARNING_GENAI"),
    "tts": ("Text-to-Speech", "DEEP_LEARNING_GENAI"),
    "speech recognition": ("Speech Recognition", "DEEP_LEARNING_GENAI"),

    # ── Additional Big Data / Data Engineering ──
    "flink": ("Apache Flink", "BIG_DATA"), "apache flink": ("Apache Flink", "BIG_DATA"),
    "hive": ("Apache Hive", "BIG_DATA"), "apache hive": ("Apache Hive", "BIG_DATA"),
    "hbase": ("HBase", "BIG_DATA"), "apache hbase": ("HBase", "BIG_DATA"),
    "presto": ("Presto", "BIG_DATA"), "trino": ("Trino", "BIG_DATA"),
    "druid": ("Apache Druid", "BIG_DATA"), "apache druid": ("Apache Druid", "BIG_DATA"),
    "nifi": ("Apache NiFi", "BIG_DATA"), "apache nifi": ("Apache NiFi", "BIG_DATA"),
    "fluentd": ("Fluentd", "BIG_DATA"), "logstash": ("Logstash", "BIG_DATA"),
    "elasticsearch": ("Elasticsearch", "BIG_DATA"), "elastic search": ("Elasticsearch", "BIG_DATA"),
    "opensearch": ("OpenSearch", "BIG_DATA"),
    "kinesis": ("AWS Kinesis", "BIG_DATA"),
    "event hub": ("Azure Event Hub", "BIG_DATA"), "event hubs": ("Azure Event Hub", "BIG_DATA"),
    "pub/sub": ("GCP Pub/Sub", "BIG_DATA"), "pubsub": ("GCP Pub/Sub", "BIG_DATA"),
    "data lake": ("Data Lake", "BIG_DATA"), "data lakehouse": ("Data Lakehouse", "BIG_DATA"),
    "data mesh": ("Data Mesh", "BIG_DATA"), "data fabric": ("Data Fabric", "BIG_DATA"),
    "data catalog": ("Data Catalog", "BIG_DATA"),
    "data governance": ("Data Governance", "DATA_MANAGEMENT"),
    "data lineage": ("Data Lineage", "DATA_MANAGEMENT"),
    "data stewardship": ("Data Stewardship", "DATA_MANAGEMENT"),
    "master data management": ("Master Data Management", "DATA_MANAGEMENT"),
    "mdm": ("Master Data Management", "DATA_MANAGEMENT"),
    "fivetran": ("Fivetran", "BIG_DATA"), "stitch": ("Stitch", "BIG_DATA"),
    "talend": ("Talend", "BIG_DATA"), "informatica": ("Informatica", "BIG_DATA"),
    "ssis": ("SSIS", "BIG_DATA"), "boomi": ("Dell Boomi", "BIG_DATA"),
    "mulesoft": ("MuleSoft", "BIG_DATA"),
    "prefect": ("Prefect", "BIG_DATA"), "dagster": ("Dagster", "BIG_DATA"),
    "luigi": ("Luigi", "BIG_DATA"),
    "synapse analytics": ("Azure Synapse", "BIG_DATA"),
    "azure synapse": ("Azure Synapse", "BIG_DATA"),
    "bigquery": ("BigQuery", "BIG_DATA"), "google bigquery": ("BigQuery", "BIG_DATA"),
    "athena": ("AWS Athena", "BIG_DATA"),

    # ── Additional Cloud / Infra ──
    "azure devops": ("Azure DevOps", "CLOUD_INFRA"),
    "azure data factory": ("Azure Data Factory", "CLOUD_INFRA"),
    "azure databricks": ("Azure Databricks", "CLOUD_INFRA"),
    "azure kubernetes": ("AKS", "CLOUD_INFRA"), "aks": ("AKS", "CLOUD_INFRA"),
    "gke": ("GKE", "CLOUD_INFRA"), "google kubernetes": ("GKE", "CLOUD_INFRA"),
    "fargate": ("AWS Fargate", "CLOUD_INFRA"),
    "ecs": ("ECS", "CLOUD_INFRA"),
    "cloudformation": ("CloudFormation", "CLOUD_INFRA"),
    "pulumi": ("Pulumi", "CLOUD_INFRA"),
    "ansible": ("Ansible", "CLOUD_INFRA"),
    "chef": ("Chef", "CLOUD_INFRA"), "puppet": ("Puppet", "CLOUD_INFRA"),
    "vault": ("HashiCorp Vault", "CLOUD_INFRA"),
    "consul": ("HashiCorp Consul", "CLOUD_INFRA"),
    "istio": ("Istio", "CLOUD_INFRA"),
    "prometheus": ("Prometheus", "CLOUD_INFRA"),
    "grafana": ("Grafana", "CLOUD_INFRA"),
    "datadog": ("Datadog", "CLOUD_INFRA"),
    "splunk": ("Splunk", "CLOUD_INFRA"),
    "new relic": ("New Relic", "CLOUD_INFRA"),
    "pagerduty": ("PagerDuty", "CLOUD_INFRA"),
    "cloudwatch": ("CloudWatch", "CLOUD_INFRA"),
    "azure monitor": ("Azure Monitor", "CLOUD_INFRA"),
    "iam": ("IAM", "CLOUD_INFRA"),
    "vpc": ("VPC Networking", "CLOUD_INFRA"),
    "route53": ("Route53", "CLOUD_INFRA"),
    "rds": ("AWS RDS", "CLOUD_INFRA"),
    "aurora": ("Aurora", "CLOUD_INFRA"),
    "dynamodb": ("DynamoDB", "CLOUD_INFRA"),
    "cosmos db": ("Cosmos DB", "CLOUD_INFRA"),
    "bigtable": ("Bigtable", "CLOUD_INFRA"),
    "spanner": ("Cloud Spanner", "CLOUD_INFRA"),
    "firestore": ("Firestore", "CLOUD_INFRA"),
    "cloud cost optimization": ("Cloud Cost Optimization", "CLOUD_INFRA"),
    "finops": ("FinOps", "CLOUD_INFRA"),
    "multi-cloud": ("Multi-Cloud", "CLOUD_INFRA"),
    "hybrid cloud": ("Hybrid Cloud", "CLOUD_INFRA"),

    # ── Additional MLOps ──
    "seldon": ("Seldon Core", "MLOPS_DEPLOYMENT"),
    "kserve": ("KServe", "MLOPS_DEPLOYMENT"),
    "torchserve": ("TorchServe", "MLOPS_DEPLOYMENT"),
    "sagemaker pipelines": ("SageMaker Pipelines", "MLOPS_DEPLOYMENT"),
    "vertex ai pipelines": ("Vertex AI Pipelines", "MLOPS_DEPLOYMENT"),
    "argo workflows": ("Argo Workflows", "MLOPS_DEPLOYMENT"),
    "airflow mlops": ("Airflow MLOps", "MLOPS_DEPLOYMENT"),
    "model registry": ("Model Registry", "MLOPS_DEPLOYMENT"),
    "feature store": ("Feature Store", "MLOPS_DEPLOYMENT"),
    "ab testing ml": ("ML A/B Testing", "MLOPS_DEPLOYMENT"),
    "shadow mode": ("Shadow Deployment", "MLOPS_DEPLOYMENT"),
    "canary deployment": ("Canary Deployment", "MLOPS_DEPLOYMENT"),
    "blue green": ("Blue-Green Deployment", "MLOPS_DEPLOYMENT"),
    "data drift": ("Data Drift Detection", "MLOPS_DEPLOYMENT"),
    "model drift": ("Model Drift Detection", "MLOPS_DEPLOYMENT"),
    "responsible ai": ("Responsible AI", "MLOPS_DEPLOYMENT"),
    "model fairness": ("Model Fairness", "MLOPS_DEPLOYMENT"),
    "model explainability": ("Model Explainability", "MLOPS_DEPLOYMENT"),
    "quantization": ("Model Quantization", "MLOPS_DEPLOYMENT"),
    "pruning": ("Model Pruning", "MLOPS_DEPLOYMENT"),
    "distillation": ("Knowledge Distillation", "MLOPS_DEPLOYMENT"),
    "lora": ("LoRA", "MLOPS_DEPLOYMENT"), "qlora": ("QLoRA", "MLOPS_DEPLOYMENT"),
    "peft": ("PEFT", "MLOPS_DEPLOYMENT"),

    # ── Additional Databases ──
    "mongodb": ("MongoDB", "DATA_MANAGEMENT"),
    "cassandra": ("Cassandra", "DATA_MANAGEMENT"),
    "couchdb": ("CouchDB", "DATA_MANAGEMENT"),
    "mariadb": ("MariaDB", "DATA_MANAGEMENT"),
    "sqlite": ("SQLite", "DATA_MANAGEMENT"),
    "oracle db": ("Oracle DB", "DATA_MANAGEMENT"),
    "ms sql server": ("SQL Server", "DATA_MANAGEMENT"), "sql server": ("SQL Server", "DATA_MANAGEMENT"),
    "db2": ("IBM DB2", "DATA_MANAGEMENT"),
    "influxdb": ("InfluxDB", "DATA_MANAGEMENT"),
    "timescaledb": ("TimescaleDB", "DATA_MANAGEMENT"),
    "redis": ("Redis", "DATA_MANAGEMENT"),
    "memcached": ("Memcached", "DATA_MANAGEMENT"),
    "etcd": ("etcd", "DATA_MANAGEMENT"),
    "arangodb": ("ArangoDB", "DATA_MANAGEMENT"),
    "tigergraph": ("TigerGraph", "DATA_MANAGEMENT"),
    "data normalization": ("Data Normalization", "DATA_MANAGEMENT"),
    "olap": ("OLAP", "DATA_MANAGEMENT"), "oltp": ("OLTP", "DATA_MANAGEMENT"),
    "star schema": ("Star Schema", "DATA_MANAGEMENT"),
    "slowly changing dimensions": ("SCD", "DATA_MANAGEMENT"), "scd": ("SCD", "DATA_MANAGEMENT"),

    # ── Additional Visualization / BI ──
    "qlik": ("Qlik", "VISUALIZATION_BI"), "qliksense": ("Qlik Sense", "VISUALIZATION_BI"),
    "microstrategy": ("MicroStrategy", "VISUALIZATION_BI"),
    "sisense": ("Sisense", "VISUALIZATION_BI"),
    "metabase": ("Metabase", "VISUALIZATION_BI"),
    "superset": ("Apache Superset", "VISUALIZATION_BI"),
    "redash": ("Redash", "VISUALIZATION_BI"),
    "google data studio": ("Looker Studio", "VISUALIZATION_BI"),
    "d3.js": ("D3.js", "VISUALIZATION_BI"), "d3": ("D3.js", "VISUALIZATION_BI"),
    "altair": ("Altair", "VISUALIZATION_BI"),
    "bokeh": ("Bokeh", "VISUALIZATION_BI"),
    "highcharts": ("Highcharts", "VISUALIZATION_BI"),
    "echarts": ("ECharts", "VISUALIZATION_BI"),
    "reportlab": ("ReportLab", "VISUALIZATION_BI"),
    "storytelling with data": ("Data Storytelling", "VISUALIZATION_BI"),
    "executive reporting": ("Executive Reporting", "VISUALIZATION_BI"),

    # ── Professional / soft skills — tracked for golden dataset and rubric scoring ──
    "international exposure": ("International Exposure", "PROFESSIONAL_SKILLS"),
    "global team": ("Global Team Experience", "PROFESSIONAL_SKILLS"),
    "global teams": ("Global Team Experience", "PROFESSIONAL_SKILLS"),
    "onsite": ("Onsite Exposure", "PROFESSIONAL_SKILLS"),
    "stakeholder management": ("Stakeholder Management", "PROFESSIONAL_SKILLS"),
    "stakeholder": ("Stakeholder Management", "PROFESSIONAL_SKILLS"),
    "client management": ("Client Management", "PROFESSIONAL_SKILLS"),
    "client facing": ("Client-Facing", "PROFESSIONAL_SKILLS"),
    "client-facing": ("Client-Facing", "PROFESSIONAL_SKILLS"),
    "cross-functional": ("Cross-functional Collaboration", "PROFESSIONAL_SKILLS"),
    "cross functional": ("Cross-functional Collaboration", "PROFESSIONAL_SKILLS"),
    "mentorship": ("Mentorship", "PROFESSIONAL_SKILLS"),
    "mentoring": ("Mentorship", "PROFESSIONAL_SKILLS"),
    "coaching": ("Coaching", "PROFESSIONAL_SKILLS"),
    "code review": ("Code Review", "PROFESSIONAL_SKILLS"),
    "code reviews": ("Code Review", "PROFESSIONAL_SKILLS"),
    "people management": ("People Management", "PROFESSIONAL_SKILLS"),
    "team lead": ("Team Leadership", "PROFESSIONAL_SKILLS"),
    "tech lead": ("Technical Leadership", "PROFESSIONAL_SKILLS"),
    "technical lead": ("Technical Leadership", "PROFESSIONAL_SKILLS"),
    "technical leadership": ("Technical Leadership", "PROFESSIONAL_SKILLS"),
    "agile": ("Agile", "PROFESSIONAL_SKILLS"),
    "scrum": ("Scrum", "PROFESSIONAL_SKILLS"),
    "product ownership": ("Product Ownership", "PROFESSIONAL_SKILLS"),
    "product owner": ("Product Ownership", "PROFESSIONAL_SKILLS"),
    "pre-sales": ("Pre-sales", "PROFESSIONAL_SKILLS"),
    "proposal writing": ("Proposal Writing", "PROFESSIONAL_SKILLS"),
    "hiring": ("Hiring / Talent Acquisition", "PROFESSIONAL_SKILLS"),
    "team building": ("Team Building", "PROFESSIONAL_SKILLS"),
}

EDUCATION_INSTITUTE_DICTIONARY = {
    "iit": {"canonical_name": "Indian Institute of Technology", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit delhi": {"canonical_name": "Indian Institute of Technology Delhi", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit bombay": {"canonical_name": "Indian Institute of Technology Bombay", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit madras": {"canonical_name": "Indian Institute of Technology Madras", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit kharagpur": {"canonical_name": "Indian Institute of Technology Kharagpur", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iisc": {"canonical_name": "Indian Institute of Science", "tier": "TIER_1", "country": "India", "category": "RESEARCH_ELITE"},
    "iisc bangalore": {"canonical_name": "Indian Institute of Science", "tier": "TIER_1", "country": "India", "category": "RESEARCH_ELITE"},
    "nit": {"canonical_name": "National Institute of Technology", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit trichy": {"canonical_name": "National Institute of Technology Tiruchirappalli", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "nit surathkal": {"canonical_name": "National Institute of Technology Karnataka", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "bits pilani": {"canonical_name": "BITS Pilani", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iiit": {"canonical_name": "Indian Institute of Information Technology", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "iiit hyderabad": {"canonical_name": "IIIT Hyderabad", "tier": "TIER_1", "country": "India", "category": "TECH_ELITE"},
    "iiit bangalore": {"canonical_name": "IIIT Bangalore", "tier": "TIER_1", "country": "India", "category": "TECH_ELITE"},
    "iim": {"canonical_name": "Indian Institute of Management", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "iim ahmedabad": {"canonical_name": "Indian Institute of Management Ahmedabad", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "iim bangalore": {"canonical_name": "Indian Institute of Management Bangalore", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "iim calcutta": {"canonical_name": "Indian Institute of Management Calcutta", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "isi": {"canonical_name": "Indian Statistical Institute", "tier": "TIER_1", "country": "India", "category": "ANALYTICS_ELITE"},
    "isi kolkata": {"canonical_name": "Indian Statistical Institute", "tier": "TIER_1", "country": "India", "category": "ANALYTICS_ELITE"},
    "delhi university": {"canonical_name": "University of Delhi", "tier": "TIER_2", "country": "India", "category": "GENERAL_STRONG"},
    "jawaharlal nehru university": {"canonical_name": "Jawaharlal Nehru University", "tier": "TIER_2", "country": "India", "category": "GENERAL_STRONG"},
    "anna university": {"canonical_name": "Anna University", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "vit": {"canonical_name": "VIT", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "manipal": {"canonical_name": "Manipal Institute of Technology", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "amity": {"canonical_name": "Amity University", "tier": "TIER_3", "country": "India", "category": "GENERAL_PRIVATE"},
    "lovely professional university": {"canonical_name": "Lovely Professional University", "tier": "TIER_3", "country": "India", "category": "GENERAL_PRIVATE"},
    "stanford": {"canonical_name": "Stanford University", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "mit": {"canonical_name": "Massachusetts Institute of Technology", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "carnegie mellon": {"canonical_name": "Carnegie Mellon University", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "oxford": {"canonical_name": "University of Oxford", "tier": "TIER_1", "country": "United Kingdom", "category": "GLOBAL_ELITE"},
    "cambridge": {"canonical_name": "University of Cambridge", "tier": "TIER_1", "country": "United Kingdom", "category": "GLOBAL_ELITE"},
    "harvard": {"canonical_name": "Harvard University", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "berkeley": {"canonical_name": "UC Berkeley", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "uc berkeley": {"canonical_name": "UC Berkeley", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "ucla": {"canonical_name": "UCLA", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "columbia": {"canonical_name": "Columbia University", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "nyu": {"canonical_name": "New York University", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "georgia tech": {"canonical_name": "Georgia Institute of Technology", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "university of toronto": {"canonical_name": "University of Toronto", "tier": "TIER_1", "country": "Canada", "category": "GLOBAL_ELITE"},
    "nus": {"canonical_name": "National University of Singapore", "tier": "TIER_1", "country": "Singapore", "category": "GLOBAL_ELITE"},
    "national university of singapore": {"canonical_name": "National University of Singapore", "tier": "TIER_1", "country": "Singapore", "category": "GLOBAL_ELITE"},
    "ntu": {"canonical_name": "Nanyang Technological University", "tier": "TIER_1", "country": "Singapore", "category": "GLOBAL_ELITE"},
    "nanyang technological university": {"canonical_name": "Nanyang Technological University", "tier": "TIER_1", "country": "Singapore", "category": "GLOBAL_ELITE"},
    "iit roorkee": {"canonical_name": "Indian Institute of Technology Roorkee", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit guwahati": {"canonical_name": "Indian Institute of Technology Guwahati", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit hyderabad": {"canonical_name": "Indian Institute of Technology Hyderabad", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "isb": {"canonical_name": "Indian School of Business", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "indian school of business": {"canonical_name": "Indian School of Business", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "xlri": {"canonical_name": "XLRI Jamshedpur", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "sp jain": {"canonical_name": "SP Jain School of Global Management", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "christ university": {"canonical_name": "Christ University", "tier": "TIER_3", "country": "India", "category": "GENERAL_PRIVATE"},
    "srm": {"canonical_name": "SRM Institute of Science and Technology", "tier": "TIER_3", "country": "India", "category": "TECH_PRIVATE"},
    "pesit": {"canonical_name": "PES Institute of Technology", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "pune university": {"canonical_name": "Savitribai Phule Pune University", "tier": "TIER_2", "country": "India", "category": "GENERAL_STRONG"},
    "mumbai university": {"canonical_name": "University of Mumbai", "tier": "TIER_2", "country": "India", "category": "GENERAL_STRONG"},
    "university of mumbai": {"canonical_name": "University of Mumbai", "tier": "TIER_2", "country": "India", "category": "GENERAL_STRONG"},
    "jadavpur university": {"canonical_name": "Jadavpur University", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "bits goa": {"canonical_name": "BITS Pilani Goa Campus", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "bits hyderabad": {"canonical_name": "BITS Pilani Hyderabad Campus", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "calcutta university": {"canonical_name": "University of Calcutta", "tier": "TIER_2", "country": "India", "category": "GENERAL_STRONG"},
    "osmania university": {"canonical_name": "Osmania University", "tier": "TIER_2", "country": "India", "category": "GENERAL_STRONG"},
    "university of hyderabad": {"canonical_name": "University of Hyderabad", "tier": "TIER_2", "country": "India", "category": "RESEARCH_STRONG"},
    "psg tech": {"canonical_name": "PSG College of Technology", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "ssn": {"canonical_name": "SSN College of Engineering", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "coimbatore institute of technology": {"canonical_name": "Coimbatore Institute of Technology", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "cit coimbatore": {"canonical_name": "Coimbatore Institute of Technology", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},

    # ── All IITs ──
    "iit kanpur": {"canonical_name": "Indian Institute of Technology Kanpur", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit bhu": {"canonical_name": "Indian Institute of Technology BHU Varanasi", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit varanasi": {"canonical_name": "Indian Institute of Technology BHU Varanasi", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit patna": {"canonical_name": "Indian Institute of Technology Patna", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit bhubaneswar": {"canonical_name": "Indian Institute of Technology Bhubaneswar", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit gandhinagar": {"canonical_name": "Indian Institute of Technology Gandhinagar", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit jodhpur": {"canonical_name": "Indian Institute of Technology Jodhpur", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit indore": {"canonical_name": "Indian Institute of Technology Indore", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit mandi": {"canonical_name": "Indian Institute of Technology Mandi", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit ropar": {"canonical_name": "Indian Institute of Technology Ropar", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit palakkad": {"canonical_name": "Indian Institute of Technology Palakkad", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit tirupati": {"canonical_name": "Indian Institute of Technology Tirupati", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit dhanbad": {"canonical_name": "Indian Institute of Technology (ISM) Dhanbad", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit ism dhanbad": {"canonical_name": "Indian Institute of Technology (ISM) Dhanbad", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit dharwad": {"canonical_name": "Indian Institute of Technology Dharwad", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit bhilai": {"canonical_name": "Indian Institute of Technology Bhilai", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit goa": {"canonical_name": "Indian Institute of Technology Goa", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit jammu": {"canonical_name": "Indian Institute of Technology Jammu", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},

    # ── Full-name aliases for IITs (LLM-extracted resumes use full names) ──
    "indian institute of technology": {"canonical_name": "Indian Institute of Technology", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "indian institute of technology kharagpur": {"canonical_name": "Indian Institute of Technology Kharagpur", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "indian institute of technology  kharagpur": {"canonical_name": "Indian Institute of Technology Kharagpur", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "indian institute of technology bombay": {"canonical_name": "Indian Institute of Technology Bombay", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "indian institute of technology delhi": {"canonical_name": "Indian Institute of Technology Delhi", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "indian institute of technology madras": {"canonical_name": "Indian Institute of Technology Madras", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "indian institute of technology kanpur": {"canonical_name": "Indian Institute of Technology Kanpur", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "indian institute of technology roorkee": {"canonical_name": "Indian Institute of Technology Roorkee", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "indian institute of technology guwahati": {"canonical_name": "Indian Institute of Technology Guwahati", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "indian institute of technology hyderabad": {"canonical_name": "Indian Institute of Technology Hyderabad", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit kgp": {"canonical_name": "Indian Institute of Technology Kharagpur", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "iit kg": {"canonical_name": "Indian Institute of Technology Kharagpur", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},

    # ── Full-name aliases for ISI ──
    "indian statistical institute": {"canonical_name": "Indian Statistical Institute", "tier": "TIER_1", "country": "India", "category": "ANALYTICS_ELITE"},
    "indian statistical institute kolkata": {"canonical_name": "Indian Statistical Institute", "tier": "TIER_1", "country": "India", "category": "ANALYTICS_ELITE"},
    "isical": {"canonical_name": "Indian Statistical Institute", "tier": "TIER_1", "country": "India", "category": "ANALYTICS_ELITE"},

    # ── Full-name aliases for IIMs ──
    "indian institute of management": {"canonical_name": "Indian Institute of Management", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "indian institute of management ahmedabad": {"canonical_name": "IIM Ahmedabad", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "indian institute of management bangalore": {"canonical_name": "IIM Bangalore", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "indian institute of management calcutta": {"canonical_name": "IIM Calcutta", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "indian institute of management kozhikode": {"canonical_name": "IIM Kozhikode", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "indian institute of management lucknow": {"canonical_name": "IIM Lucknow", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "indian institute of management indore": {"canonical_name": "IIM Indore", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},

    # ── All NITs ──
    "nit warangal": {"canonical_name": "NIT Warangal", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "nit calicut": {"canonical_name": "NIT Calicut", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "nit rourkela": {"canonical_name": "NIT Rourkela", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "nit allahabad": {"canonical_name": "MNNIT Allahabad", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "mnnit": {"canonical_name": "MNNIT Allahabad", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit nagpur": {"canonical_name": "VNIT Nagpur", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "vnit": {"canonical_name": "VNIT Nagpur", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit bhopal": {"canonical_name": "MANIT Bhopal", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "manit": {"canonical_name": "MANIT Bhopal", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit jaipur": {"canonical_name": "MNIT Jaipur", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "mnit": {"canonical_name": "MNIT Jaipur", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit surat": {"canonical_name": "SVNIT Surat", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "svnit": {"canonical_name": "SVNIT Surat", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit kurukshetra": {"canonical_name": "NIT Kurukshetra", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit hamirpur": {"canonical_name": "NIT Hamirpur", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit patna": {"canonical_name": "NIT Patna", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit durgapur": {"canonical_name": "NIT Durgapur", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit silchar": {"canonical_name": "NIT Silchar", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit jalandhar": {"canonical_name": "NIT Jalandhar", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit uttarakhand": {"canonical_name": "NIT Uttarakhand", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit puducherry": {"canonical_name": "NIT Puducherry", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit sikkim": {"canonical_name": "NIT Sikkim", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit manipur": {"canonical_name": "NIT Manipur", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit meghalaya": {"canonical_name": "NIT Meghalaya", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit nagaland": {"canonical_name": "NIT Nagaland", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit mizoram": {"canonical_name": "NIT Mizoram", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit arunachal": {"canonical_name": "NIT Arunachal Pradesh", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit goa": {"canonical_name": "NIT Goa", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit delhi": {"canonical_name": "NIT Delhi", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit andhra pradesh": {"canonical_name": "NIT Andhra Pradesh", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},

    # ── IIITs ──
    "iiit allahabad": {"canonical_name": "IIIT Allahabad", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "iiit delhi": {"canonical_name": "IIIT Delhi", "tier": "TIER_1", "country": "India", "category": "TECH_ELITE"},
    "iiit pune": {"canonical_name": "IIIT Pune", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "iiit vadodara": {"canonical_name": "IIIT Vadodara", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "iiit naya raipur": {"canonical_name": "IIIT Naya Raipur", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "iiit lucknow": {"canonical_name": "IIIT Lucknow", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "iiit kalyani": {"canonical_name": "IIIT Kalyani", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "iiit bhopal": {"canonical_name": "IIIT Bhopal", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "iiit kanchipuram": {"canonical_name": "IIIT Kanchipuram", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "iiit kota": {"canonical_name": "IIIT Kota", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "iiit srirangam": {"canonical_name": "IIIT Srirangam", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "iiit dharwad": {"canonical_name": "IIIT Dharwad", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "iiit ranchi": {"canonical_name": "IIIT Ranchi", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "iiit nagpur": {"canonical_name": "IIIT Nagpur", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "iiit manipur": {"canonical_name": "IIIT Manipur", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},

    # ── IIMs ──
    "iim lucknow": {"canonical_name": "IIM Lucknow", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "iim kozhikode": {"canonical_name": "IIM Kozhikode", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "iim indore": {"canonical_name": "IIM Indore", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "iim shillong": {"canonical_name": "IIM Shillong", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "iim rohtak": {"canonical_name": "IIM Rohtak", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "iim raipur": {"canonical_name": "IIM Raipur", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "iim ranchi": {"canonical_name": "IIM Ranchi", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "iim kashipur": {"canonical_name": "IIM Kashipur", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "iim udaipur": {"canonical_name": "IIM Udaipur", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "iim trichy": {"canonical_name": "IIM Tiruchirappalli", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "iim bodhgaya": {"canonical_name": "IIM Bodh Gaya", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "iim visakhapatnam": {"canonical_name": "IIM Visakhapatnam", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "iim nagpur": {"canonical_name": "IIM Nagpur", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "iim sirmaur": {"canonical_name": "IIM Sirmaur", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "iim sambalpur": {"canonical_name": "IIM Sambalpur", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "iim jammu": {"canonical_name": "IIM Jammu", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "iim amritsar": {"canonical_name": "IIM Amritsar", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},

    # ── More prominent Indian institutions ──
    "tiss": {"canonical_name": "Tata Institute of Social Sciences", "tier": "TIER_1", "country": "India", "category": "RESEARCH_ELITE"},
    "ximb": {"canonical_name": "Xavier Institute of Management Bhubaneswar", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "imt ghaziabad": {"canonical_name": "IMT Ghaziabad", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "great lakes": {"canonical_name": "Great Lakes Institute of Management", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "imtg": {"canonical_name": "IMT Ghaziabad", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "fore school": {"canonical_name": "FORE School of Management", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "liba": {"canonical_name": "Loyola Institute of Business Administration", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "sibm pune": {"canonical_name": "Symbiosis Institute of Business Management Pune", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "symbiosis": {"canonical_name": "Symbiosis International University", "tier": "TIER_2", "country": "India", "category": "GENERAL_STRONG"},
    "nmims": {"canonical_name": "NMIMS University", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "jbims": {"canonical_name": "Jamnalal Bajaj Institute of Management Studies", "tier": "TIER_2", "country": "India", "category": "MBA_STRONG"},
    "spjimr": {"canonical_name": "S.P. Jain Institute of Management and Research", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "iift": {"canonical_name": "Indian Institute of Foreign Trade", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "fms delhi": {"canonical_name": "Faculty of Management Studies Delhi", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "dms iit delhi": {"canonical_name": "DMS IIT Delhi", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "sjmsom": {"canonical_name": "Shailesh J. Mehta School of Management IIT Bombay", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "nitie": {"canonical_name": "NITIE Mumbai", "tier": "TIER_1", "country": "India", "category": "MBA_ELITE"},
    "teri": {"canonical_name": "TERI School of Advanced Studies", "tier": "TIER_2", "country": "India", "category": "RESEARCH_STRONG"},
    "iiser": {"canonical_name": "Indian Institute of Science Education and Research", "tier": "TIER_1", "country": "India", "category": "RESEARCH_ELITE"},
    "iiser pune": {"canonical_name": "IISER Pune", "tier": "TIER_1", "country": "India", "category": "RESEARCH_ELITE"},
    "iiser kolkata": {"canonical_name": "IISER Kolkata", "tier": "TIER_1", "country": "India", "category": "RESEARCH_ELITE"},
    "iiser bhopal": {"canonical_name": "IISER Bhopal", "tier": "TIER_1", "country": "India", "category": "RESEARCH_ELITE"},
    "iiser mohali": {"canonical_name": "IISER Mohali", "tier": "TIER_1", "country": "India", "category": "RESEARCH_ELITE"},
    "tifr": {"canonical_name": "Tata Institute of Fundamental Research", "tier": "TIER_1", "country": "India", "category": "RESEARCH_ELITE"},
    "cmi": {"canonical_name": "Chennai Mathematical Institute", "tier": "TIER_1", "country": "India", "category": "RESEARCH_ELITE"},
    "imsc": {"canonical_name": "Institute of Mathematical Sciences", "tier": "TIER_1", "country": "India", "category": "RESEARCH_ELITE"},
    "dtu": {"canonical_name": "Delhi Technological University", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "delhi technological university": {"canonical_name": "Delhi Technological University", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nsut": {"canonical_name": "Netaji Subhas University of Technology", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "igdtuw": {"canonical_name": "Indira Gandhi Delhi Technical University for Women", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "bms college": {"canonical_name": "BMS College of Engineering", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "rv college": {"canonical_name": "RV College of Engineering", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "ms ramaiah": {"canonical_name": "M.S. Ramaiah Institute of Technology", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "msrit": {"canonical_name": "M.S. Ramaiah Institute of Technology", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "rvce": {"canonical_name": "RV College of Engineering", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "bmsce": {"canonical_name": "BMS College of Engineering", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "mit manipal": {"canonical_name": "Manipal Institute of Technology", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "mitm": {"canonical_name": "Manipal Institute of Technology Manipal", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "srm university": {"canonical_name": "SRM Institute of Science and Technology", "tier": "TIER_3", "country": "India", "category": "TECH_PRIVATE"},
    "vit vellore": {"canonical_name": "VIT Vellore", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "vit chennai": {"canonical_name": "VIT Chennai", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "thapar": {"canonical_name": "Thapar Institute of Engineering and Technology", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "pec chandigarh": {"canonical_name": "Punjab Engineering College", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "pec": {"canonical_name": "Punjab Engineering College", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nit tiruchirappalli": {"canonical_name": "NIT Tiruchirappalli", "tier": "TIER_1", "country": "India", "category": "ENGINEERING_ELITE"},
    "karnataka university": {"canonical_name": "Karnatak University", "tier": "TIER_3", "country": "India", "category": "GENERAL_STRONG"},
    "bu bhopal": {"canonical_name": "Barkatullah University", "tier": "TIER_3", "country": "India", "category": "GENERAL_PRIVATE"},
    "mgu kottayam": {"canonical_name": "Mahatma Gandhi University Kottayam", "tier": "TIER_3", "country": "India", "category": "GENERAL_STRONG"},
    "kerala university": {"canonical_name": "University of Kerala", "tier": "TIER_3", "country": "India", "category": "GENERAL_STRONG"},
    "calicut university": {"canonical_name": "University of Calicut", "tier": "TIER_3", "country": "India", "category": "GENERAL_STRONG"},
    "bu pune": {"canonical_name": "Bharati Vidyapeeth University", "tier": "TIER_3", "country": "India", "category": "GENERAL_PRIVATE"},
    "mit pune": {"canonical_name": "MIT College of Engineering Pune", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "coep": {"canonical_name": "College of Engineering Pune", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "college of engineering pune": {"canonical_name": "College of Engineering Pune", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nirma university": {"canonical_name": "Nirma University", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},
    "pdpu": {"canonical_name": "Pandit Deendayal Energy University", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "upes": {"canonical_name": "University of Petroleum and Energy Studies", "tier": "TIER_3", "country": "India", "category": "TECH_PRIVATE"},
    "lpu": {"canonical_name": "Lovely Professional University", "tier": "TIER_3", "country": "India", "category": "GENERAL_PRIVATE"},
    "chandigarh university": {"canonical_name": "Chandigarh University", "tier": "TIER_3", "country": "India", "category": "TECH_PRIVATE"},
    "chitkara university": {"canonical_name": "Chitkara University", "tier": "TIER_3", "country": "India", "category": "TECH_PRIVATE"},
    "graphics era": {"canonical_name": "Graphic Era University", "tier": "TIER_3", "country": "India", "category": "TECH_PRIVATE"},
    "hit haldia": {"canonical_name": "Haldia Institute of Technology", "tier": "TIER_3", "country": "India", "category": "ENGINEERING_PRIVATE"},
    "jss": {"canonical_name": "JSS Science and Technology University", "tier": "TIER_2", "country": "India", "category": "ENGINEERING_STRONG"},
    "nie mysore": {"canonical_name": "National Institute of Engineering Mysore", "tier": "TIER_3", "country": "India", "category": "ENGINEERING_PRIVATE"},
    "kiit": {"canonical_name": "Kalinga Institute of Industrial Technology", "tier": "TIER_2", "country": "India", "category": "TECH_STRONG"},

    # ── Online / Professional / Global ──
    "coursera": {"canonical_name": "Coursera", "tier": "TIER_3", "country": "Online", "category": "ONLINE_CERT"},
    "udemy": {"canonical_name": "Udemy", "tier": "TIER_3", "country": "Online", "category": "ONLINE_CERT"},
    "edx": {"canonical_name": "edX", "tier": "TIER_3", "country": "Online", "category": "ONLINE_CERT"},
    "upgrad": {"canonical_name": "upGrad", "tier": "TIER_3", "country": "Online", "category": "ONLINE_CERT"},
    "great learning": {"canonical_name": "Great Learning", "tier": "TIER_3", "country": "Online", "category": "ONLINE_CERT"},
    "simplilearn": {"canonical_name": "Simplilearn", "tier": "TIER_3", "country": "Online", "category": "ONLINE_CERT"},
    "analytics vidhya": {"canonical_name": "Analytics Vidhya", "tier": "TIER_3", "country": "Online", "category": "ONLINE_CERT"},
    "fast.ai": {"canonical_name": "Fast.ai", "tier": "TIER_2", "country": "Online", "category": "ONLINE_CERT"},
    "deeplearning.ai": {"canonical_name": "DeepLearning.AI", "tier": "TIER_2", "country": "Online", "category": "ONLINE_CERT"},

    # ── More Global Universities ──
    "eth zurich": {"canonical_name": "ETH Zurich", "tier": "TIER_1", "country": "Switzerland", "category": "GLOBAL_ELITE"},
    "imperial college london": {"canonical_name": "Imperial College London", "tier": "TIER_1", "country": "United Kingdom", "category": "GLOBAL_ELITE"},
    "imperial college": {"canonical_name": "Imperial College London", "tier": "TIER_1", "country": "United Kingdom", "category": "GLOBAL_ELITE"},
    "ucl": {"canonical_name": "University College London", "tier": "TIER_1", "country": "United Kingdom", "category": "GLOBAL_ELITE"},
    "edinburgh": {"canonical_name": "University of Edinburgh", "tier": "TIER_1", "country": "United Kingdom", "category": "GLOBAL_ELITE"},
    "university of edinburgh": {"canonical_name": "University of Edinburgh", "tier": "TIER_1", "country": "United Kingdom", "category": "GLOBAL_ELITE"},
    "epfl": {"canonical_name": "EPFL", "tier": "TIER_1", "country": "Switzerland", "category": "GLOBAL_ELITE"},
    "tu munich": {"canonical_name": "Technical University of Munich", "tier": "TIER_1", "country": "Germany", "category": "GLOBAL_ELITE"},
    "tum": {"canonical_name": "Technical University of Munich", "tier": "TIER_1", "country": "Germany", "category": "GLOBAL_ELITE"},
    "university of washington": {"canonical_name": "University of Washington", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "uw": {"canonical_name": "University of Washington", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "uiuc": {"canonical_name": "University of Illinois Urbana-Champaign", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "university of michigan": {"canonical_name": "University of Michigan", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "university of texas": {"canonical_name": "University of Texas at Austin", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "ut austin": {"canonical_name": "University of Texas at Austin", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "purdue": {"canonical_name": "Purdue University", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "cornell": {"canonical_name": "Cornell University", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "yale": {"canonical_name": "Yale University", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "princeton": {"canonical_name": "Princeton University", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "caltech": {"canonical_name": "Caltech", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "penn state": {"canonical_name": "Penn State University", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "nc state": {"canonical_name": "NC State University", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "university of southern california": {"canonical_name": "USC", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "usc": {"canonical_name": "USC", "tier": "TIER_1", "country": "United States", "category": "GLOBAL_ELITE"},
    "waterloo": {"canonical_name": "University of Waterloo", "tier": "TIER_1", "country": "Canada", "category": "GLOBAL_ELITE"},
    "university of waterloo": {"canonical_name": "University of Waterloo", "tier": "TIER_1", "country": "Canada", "category": "GLOBAL_ELITE"},
    "mcgill": {"canonical_name": "McGill University", "tier": "TIER_1", "country": "Canada", "category": "GLOBAL_ELITE"},
    "ubc": {"canonical_name": "University of British Columbia", "tier": "TIER_1", "country": "Canada", "category": "GLOBAL_ELITE"},
    "university of melbourne": {"canonical_name": "University of Melbourne", "tier": "TIER_1", "country": "Australia", "category": "GLOBAL_ELITE"},
    "anu": {"canonical_name": "Australian National University", "tier": "TIER_1", "country": "Australia", "category": "GLOBAL_ELITE"},
    "unsw": {"canonical_name": "UNSW Sydney", "tier": "TIER_1", "country": "Australia", "category": "GLOBAL_ELITE"},
    "bits dubai": {"canonical_name": "BITS Pilani Dubai Campus", "tier": "TIER_2", "country": "UAE", "category": "ENGINEERING_STRONG"},
    "university of amsterdam": {"canonical_name": "University of Amsterdam", "tier": "TIER_1", "country": "Netherlands", "category": "GLOBAL_ELITE"},
    "ku leuven": {"canonical_name": "KU Leuven", "tier": "TIER_1", "country": "Belgium", "category": "GLOBAL_ELITE"},
    "paris saclay": {"canonical_name": "University of Paris-Saclay", "tier": "TIER_1", "country": "France", "category": "GLOBAL_ELITE"},
    "peking university": {"canonical_name": "Peking University", "tier": "TIER_1", "country": "China", "category": "GLOBAL_ELITE"},
    "tsinghua": {"canonical_name": "Tsinghua University", "tier": "TIER_1", "country": "China", "category": "GLOBAL_ELITE"},
    "iitm pravartak": {"canonical_name": "IITM Pravartak", "tier": "TIER_2", "country": "India", "category": "ONLINE_CERT"},
}

COURSE_DICTIONARY = {
    "b.tech": {"canonical_name": "B.Tech", "family": "ENGINEERING", "value_signal": "HIGH"},
    "btech": {"canonical_name": "B.Tech", "family": "ENGINEERING", "value_signal": "HIGH"},
    "be": {"canonical_name": "B.E.", "family": "ENGINEERING", "value_signal": "HIGH"},
    "b.e": {"canonical_name": "B.E.", "family": "ENGINEERING", "value_signal": "HIGH"},
    "m.tech": {"canonical_name": "M.Tech", "family": "ENGINEERING", "value_signal": "HIGH"},
    "mtech": {"canonical_name": "M.Tech", "family": "ENGINEERING", "value_signal": "HIGH"},
    # Common CS/IT field names as field_of_study values
    "computer science": {"canonical_name": "Computer Science", "family": "ENGINEERING", "value_signal": "HIGH"},
    "computer science and engineering": {"canonical_name": "CSE", "family": "ENGINEERING", "value_signal": "HIGH"},
    "computer engineering": {"canonical_name": "Computer Engineering", "family": "ENGINEERING", "value_signal": "HIGH"},
    "information technology": {"canonical_name": "Information Technology", "family": "ENGINEERING", "value_signal": "HIGH"},
    "software engineering": {"canonical_name": "Software Engineering", "family": "ENGINEERING", "value_signal": "HIGH"},
    "electronics and communication": {"canonical_name": "ECE", "family": "ENGINEERING", "value_signal": "HIGH"},
    "electronics and communication engineering": {"canonical_name": "ECE", "family": "ENGINEERING", "value_signal": "HIGH"},
    "electrical engineering": {"canonical_name": "Electrical Engineering", "family": "ENGINEERING", "value_signal": "HIGH"},
    "mechanical engineering": {"canonical_name": "Mechanical Engineering", "family": "ENGINEERING", "value_signal": "HIGH"},
    "civil engineering": {"canonical_name": "Civil Engineering", "family": "ENGINEERING", "value_signal": "HIGH"},
    "bsc": {"canonical_name": "B.Sc", "family": "SCIENCE", "value_signal": "MEDIUM"},
    "msc": {"canonical_name": "M.Sc", "family": "SCIENCE", "value_signal": "MEDIUM"},
    "bca": {"canonical_name": "BCA", "family": "COMPUTER_APPLICATIONS", "value_signal": "MEDIUM"},
    "mca": {"canonical_name": "MCA", "family": "COMPUTER_APPLICATIONS", "value_signal": "HIGH"},
    "mba": {"canonical_name": "MBA", "family": "MANAGEMENT", "value_signal": "HIGH"},
    "pgdm": {"canonical_name": "PGDM", "family": "MANAGEMENT", "value_signal": "HIGH"},
    "pdgm": {"canonical_name": "PGDM", "family": "MANAGEMENT", "value_signal": "HIGH"},
    "b.com": {"canonical_name": "B.Com", "family": "COMMERCE", "value_signal": "MEDIUM"},
    "m.com": {"canonical_name": "M.Com", "family": "COMMERCE", "value_signal": "MEDIUM"},
    "ba": {"canonical_name": "B.A.", "family": "ARTS", "value_signal": "FOUNDATIONAL"},
    "ma": {"canonical_name": "M.A.", "family": "ARTS", "value_signal": "FOUNDATIONAL"},
    "phd": {"canonical_name": "PhD", "family": "RESEARCH", "value_signal": "HIGH"},
    "doctor of philosophy": {"canonical_name": "PhD", "family": "RESEARCH", "value_signal": "HIGH"},
    # ── Quantitative / Analytics / Statistics degrees ──
    # These are treated as HIGH relevance for data science / analytics roles
    "statistics": {"canonical_name": "Statistics", "family": "ANALYTICS", "value_signal": "HIGH"},
    "applied statistics": {"canonical_name": "Applied Statistics", "family": "ANALYTICS", "value_signal": "HIGH"},
    "quantitative economics": {"canonical_name": "Quantitative Economics", "family": "ANALYTICS", "value_signal": "HIGH"},
    "msqe": {"canonical_name": "M.Sc Quantitative Economics", "family": "ANALYTICS", "value_signal": "HIGH"},
    "m.sc quantitative economics": {"canonical_name": "M.Sc Quantitative Economics", "family": "ANALYTICS", "value_signal": "HIGH"},
    "econometrics": {"canonical_name": "Econometrics", "family": "ANALYTICS", "value_signal": "HIGH"},
    "operations research": {"canonical_name": "Operations Research", "family": "ANALYTICS", "value_signal": "HIGH"},
    "mathematical statistics": {"canonical_name": "Mathematical Statistics", "family": "ANALYTICS", "value_signal": "HIGH"},
    "actuarial science": {"canonical_name": "Actuarial Science", "family": "ANALYTICS", "value_signal": "HIGH"},
    "data science": {"canonical_name": "Data Science", "family": "ANALYTICS", "value_signal": "HIGH"},
    "m.sc data science": {"canonical_name": "M.Sc Data Science", "family": "ANALYTICS", "value_signal": "HIGH"},
    "analytics": {"canonical_name": "Analytics", "family": "ANALYTICS", "value_signal": "HIGH"},
    "business analytics": {"canonical_name": "Business Analytics", "family": "ANALYTICS", "value_signal": "HIGH"},
    "machine learning": {"canonical_name": "Machine Learning", "family": "ANALYTICS", "value_signal": "HIGH"},
    "artificial intelligence": {"canonical_name": "Artificial Intelligence", "family": "ANALYTICS", "value_signal": "HIGH"},
}

GPA_BENCHMARKS = {
    "10_POINT": {"excellent": 8.5, "good": 7.5, "acceptable": 6.5},
    "4_POINT": {"excellent": 3.7, "good": 3.2, "acceptable": 2.8},
    "100_POINT": {"excellent": 85, "good": 75, "acceptable": 65},
}
